// Angular
import 'rxjs';
import '@angular/core';
import '@angular/common';
import '@angular/forms';
import '@angular/router';
import '@angular/http';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';